spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mcloud?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    bk-login:
        dev: true
        dev-username: admin
        api: http://localhost:8003/
        redirect: http://localhost:8003/
        cookie: bk_token
