spring:
    profiles:
        active: dev
    jpa:
        database: MySQL
        show-sql: false
    jcasbin:
#        model-path: /conf/rbac_with_resource_roles.conf
        model: |-
            [request_definition]
            r = sub, obj, act

            [policy_definition]
            p = sub, obj, act

            [role_definition]
            g = _, _
            g2 = _, _

            [policy_effect]
            e = some(where (p.eft == allow))

            [matchers]
            m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act || r.sub == "admin" || g(r.sub, "ADMIN")
server:
    servlet:
        context-path: /cmdb/torn-mcloud/
        session:
            timeout: 864000
    compression:
        enabled: true
        mime-types: text/javascript,application/javascript,text/css
